### ISSUE TITLE
why is logging function not a normal smoof function

### ISSUE THREAD

**Issue by berndbischl** [jakobbossek/smoof#101]
this seems to violate the expected inheritance contract

tf = makeBraninFunction()
tf = addLoggingWrapper(tf)
class(tf)
[1] "smoof_logging_function" "smoof_wrapped_function"

thats a bit weird, right? 
because i can use it like a normal smoof_function

https://github.com/mlr-org/mlrMBO/issues/393

**Comment by jakobbossek** [comment]
Thanks for pointing this out. Fixed.

**Comment by berndbischl** [comment]
@jakobbossek 
could you push this fix to cran please? this breaks lots of things.....
