### ISSUE TITLE
Conversion doesn´t flip Optima

### ISSUE THREAD

**Issue by surmann** [jakobbossek/smoof#105]
When I change the optimisation direction via `convertToMinimization` the value of the optima should change, too. It is difficult to get the information from the output of `getGlobalOptimum` that I have to multiply `$value` by `-1`.

> packageVersion("smoof")
> #[1] ‘1.5’
> obj.fun = makeAlpine02Function(2)
> getGlobalOptimum(obj.fun)
> #$value
> #[1] 7.884864
> #$is.minimum
> #[1] FALSE
> obj.fun = convertToMinimization(obj.fun)
> getGlobalOptimum(obj.fun)
> #$value
> #[1] 7.884864
> #$is.minimum
> #[1] TRUE

What do you think?

**Comment by jakobbossek** [comment]
I think you found an embarrassing bug sir!

**Comment by jakobbossek** [comment]
Fixed.
