### ISSUE TITLE
Next mail from CRAN:

### ISSUE THREAD

**Issue by jakobbossek** [jakobbossek/smoof#126]
Nice! An error on solaris. Not even sure if the error raised is the only problematic lines of code.

> Dear maintainer,
>
> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_smoof.html>.

> Please correct before 2020-01-31 to safely retain your package on CRAN.

> The CRAN Team

**Comment by fcampelo** [comment]
Now a problem in windows, related to package rPython not being available. 

Also: the package is showing as `orphaned` on CRAN - you may have accidentally messed up the DESCRIPTION in the last emergency update (or maybe changed maintainer emails and did not confirm the change on the old address?)

**Comment by mllg** [comment]
Solaris now works, maybe BR hotfixed it in 1.6.1?

**Comment by jakobbossek** [comment]
Yep. CRAN team fixed it on Solaris. It was a single line fix.
