### ISSUE TITLE
CRAN Status: orphaned

### ISSUE THREAD

**Issue by jakob-r** [jakobbossek/smoof#127]
Hi Jakob,
we will run into problems with CRAN depending on `smoof` it the status is orphaned. Do you have time to fix this issue? What is your plan here?

**Comment by jakobbossek** [comment]
Going to fix this tomorrow.

**Comment by bryanhanson** [comment]
I need a fix too -- did `smoof`, `ParamHelpers` and/or `mlr` move to `mlr3`?  On first look I don't see them there.  Thank you.

**Comment by jakob-r** [comment]
@bryanhanson `mlr3` is independent of `smoof` and `ParamHelpers`. However, we will still maintain `ParamHelpers` and `mlr`. Also @jakobbossek will still maintain `smoof` I hope :)

**Comment by jakobbossek** [comment]
Sure, I will continue maintaining smoof 👍🏼
Will fix the orphaned status in a couple of days. Taking some time off at the moment due to heavy workload in the past weeks.

**Comment by jakobbossek** [comment]
smoof 1.6.0.2 is on it’s way to CRAN.
