### ISSUE TITLE
Consider "Suggesting" plot libraries instead of "Importing" them

### ISSUE THREAD

**Issue by mb706** [jakobbossek/smoof#132]
`smoof` is useful as a framework to define objective functions for optimization, used in this way e.g. by `mlrMBO`. It would be nice if `smoof` could be installed with fewer heavy dependencies when plotting is not needed. Especially `plot3D`, which apparently makes `smoof` fail on Mac when X11 is not installed (I don't have a Mac myself but I am seeing this in github action failures).

**Comment by jakobbossek** [comment]
Good point. Will implement this soon 👍

**Comment by jakobbossek** [comment]
Done via bf442a6
