### ISSUE TITLE
Implement extended bi-objective BBOB functions

### ISSUE THREAD

**Issue by schaepermeier** [jakobbossek/smoof#140]
After the bi-objective BBOB was introduced, it was extended shortly after by further function combinations. The extended bi-objective BBOB consists of 92 function IDs overall, of which the first 55 are identical to the original bi-objective BBOB, i.e. FIDs 56-92 are new in the "extended" version of the benchmark. They should be available in smoof, and I think the best place to add them is `makeBiObjBBOBFunction` as it just consists of adding the new function combinations.

See http://numbbo.github.io/coco-doc/bbob-biobj/functions/#the-extended-bbob-biobj-ext-test-suite-and-its-functions
and https://arxiv.org/pdf/1604.00359.pdf.

Any thoughts?

**Comment by jakobbossek** [comment]
Hi Lennart, sounds good. Happy to merge a PR.

**Comment by jakobbossek** [comment]
Merged pull request 🚀
