### ISSUE TITLE
How to install rPython with R 3.1.3 on Windows?

### ISSUE THREAD

**Issue by surmann** [jakobbossek/smoof#40]
How do I install `rPython` with R 3.1.3 on Windows OS?
An `install.packages("rPython")` from the austrian repo throws me the warning: "package rPython not available". The installation guide from [rForge](http://rpython.r-forge.r-project.org/) gives the same one.

**Comment by jakobbossek** [comment]
Oh damn! rPython does not work on windows systems at the moment.

**Comment by jakobbossek** [comment]
Hmm, at the moment it is not possible to call python via rPython on Windows OS. Sure, I could just check whether the used OS is windows and throw an error message in that case for the mpm2 generator. However, the problem is that I need to note rPyhon in the Imports section in the DESCRIPTION file. This way the installation of smoof breaks under windows, since rPython is not available. At the moment I gave no clue how to solve this. In the worst-case I will outsource the mpm2 stuff to a single UNIX-only package.

**Comment by surmann** [comment]
My problem with this issue: I cannot use the `ecr` package without `smoof` which is not installable without `rPython`.

**Comment by surmann** [comment]
I installed (rPython-win)[https://github.com/cjgb/rPython-win]. Unfortunately, the package contains version 0.0-4.

**Comment by jakobbossek** [comment]
I will tackle this problem on monday.

**Comment by jakobbossek** [comment]
I moved rPython to Suggests. By default it should not be installed now. The python-dependent function should throw an error now on windows systems. Dirk, could you please check the latest build on you windows system?

**Comment by surmann** [comment]
I'm able to check smoof by `check(".", force_suggests = TRUE)`. When I try to install the package by `dt` or from the R console directly, I get the following result:
```R
> install(".", dependencies=c("Depends", "Imports", "LinkingTo"))
Installing smoof
"C:/PROGRA~1/R/R-31~1.3/bin/x64/R" --vanilla CMD INSTALL  \
  "C:/Users/surmann/Documents/Repositories/smoof"  \
  --library="C:/Users/surmann/Documents/R/win-library/3.1" --install-tests 

* installing *source* package 'smoof' ...
** libs

*** arch - i386
make: Nothing to be done for `all'.
installing to C:/Users/surmann/Documents/R/win-library/3.1/smoof/libs/i386

*** arch - x64
make: Nothing to be done for `all'.
installing to C:/Users/surmann/Documents/R/win-library/3.1/smoof/libs/x64
** R
** inst
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  kann shared object 'C:/Users/surmann/Documents/R/win-library/3.1/smoof/libs/x64/smoof.dll' nicht laden:
  LoadLibrary failure:  %1 ist keine zulässige Win32-Anwendung.

Fehler: Laden fehlgeschlagen
Ausführung angehalten
ERROR: loading failed for 'x64'
* removing 'C:/Users/surmann/Documents/R/win-library/3.1/smoof'
* restoring previous 'C:/Users/surmann/Documents/R/win-library/3.1/smoof'
Error: Command failed (1)
```
Do you have an idea? I tried R 32-bit and 64-bit.

**Comment by jakobbossek** [comment]
Oh man! Since this error is referred to the generated dynamic link library (dll) I suppose this is a problem with the c(++) stuff.

**Comment by jakobbossek** [comment]
Going to check this on a windows machine soon.

**Comment by jakobbossek** [comment]
Well, I just successfully installed the latest commit via `devtools::install_github("jakobbossek/smoof")` on a Windows 7 machine with R version 3.1.1. No problems occured. I will check this in the evening on my home pc with the newest R version.

**Comment by surmann** [comment]
Arg. I tried it this way and it works.
After I deleted the directories `scr-*` manually, a `dt install` works too. We should add this in `dt clean`.

**Comment by jakobbossek** [comment]
Ok, can I close this issue?
You should open a new issue in the dt issue tracker and describe the problem there.

**Comment by surmann** [comment]
solved
