### ISSUE TITLE
Error with `dt check` on Windows 8

### ISSUE THREAD

**Issue by surmann** [jakobbossek/smoof#41]
Hallo Jakob,

sorry for bothering you with all that Windows stuff.
I made a `dt check` on the commit 66c4c368966ea6fe6323554603bad370215105cc with my Windows 8 system and got the attached log file. Do you have any glue why the `x` in line 55 converted?

All best,
Dirk

Log-File:
<pre><code>* using log directory 'C:/Users/Dirk/Documents/Repositories/smoof/smoof.Rcheck'
* using R version 3.1.3 (2015-03-09)
* using platform: i386-w64-mingw32 (32-bit)
* using session charset: ISO8859-1
* checking for file 'smoof/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'smoof' version '1.0'
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package 'smoof' can be installed ... [13s] OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* loading checks for arch 'i386'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ... OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies ... OK
** checking whether the namespace can be unloaded cleanly ... OK
** checking loading without being on the library search path ... OK
* loading checks for arch 'x64'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ... OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies ... OK
** checking whether the namespace can be unloaded cleanly ... OK
** checking loading without being on the library search path ... OK
* checking dependencies in R code ... WARNING
'::' or ':::' import not declared from: 'rPython'
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... WARNING
plot3D.Rd: non-ASCII input and no declared encoding
problem found in 'plot3D.Rd'
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'plot3D'
  'x'
Documented arguments not in \usage in documentation object 'plot3D':
  'xÂ'

Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter 'Writing R documentation files' in the 'Writing R
Extensions' manual.
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking compiled code ... OK
* checking examples ...
** running examples for arch 'i386' ... ERROR
Running examples in 'smoof-Ex.R' failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: makeFunnelFunction
> ### Title: Generator for funnel-like functions.
> ### Aliases: makeFunnelFunction
> 
> ### ** Examples
> 
> # Unfortunately
> fn = makeFunnelFunction(n.peaks = 10L, dimension = 2L, topology = "funnel", seed = 123)
Error: could not find function "makeFunnelFunction"
Execution halted
** running examples for arch 'x64' ... ERROR
Running examples in 'smoof-Ex.R' failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: makeFunnelFunction
> ### Title: Generator for funnel-like functions.
> ### Aliases: makeFunnelFunction
> 
> ### ** Examples
> 
> # Unfortunately
> fn = makeFunnelFunction(n.peaks = 10L, dimension = 2L, topology = "funnel", seed = 123)
Error: could not find function "makeFunnelFunction"
Execution halted</code></pre>

**Comment by jakobbossek** [comment]
Hi Dirk,

a first question: why do you not use the latest commited version?

> sorry for bothering you with all that Windows stuff.
> I made a dt check on the commit 66c4c36 with my Windows 8 system and got the attached log file. Do > you have any glue why the x in line 55 converted?

I am very thankful for every issue documentation here in the issue tracker :+1:
Actually my OS X system did not complain about that, but my text editor highlighted the documentation line in a weird unfamiliar color. Rewrote the line. Should be fixed now. Some non-ascii letter was hidden somewhere.

The error message regarding the unknown `makeFunnelFunction` has been already fixed, but I suppose `dt check` will still fail on your windows 8 system due to the rPython problem (see #40 and #38).

Can we close this?

**Comment by surmann** [comment]
This is the last commit without rPython.
Thanks for solving this.
