### ISSUE TITLE
Parameter definition vs. function call

### ISSUE THREAD

**Issue by surmann** [jakobbossek/smoof#43]
Hallo Jakob,

The Rastrigin function can be defined with e.g. two dimensions: `makeRastriginFunction(2L)`, which give a parameter set with two numerics. However, the function take a vector of length two, not two numerics. Would it be consistent to define a parameter vector or multiple arguments in the function?

All best
Dirk

**Comment by jakobbossek** [comment]
Good point! Changed it. Now the predefined functions return a ParamSet with a single numeric vector parameter.
