### ISSUE TITLE
stupid question: how to figure out if function should be minimized or maximized?

### ISSUE THREAD

**Issue by berndbischl** [jakobbossek/smoof#48]

**Comment by jakobbossek** [comment]
I added an additional attribute `minimize` which expects a logical vector indicating which objectives should be minimized or maximized respectively. This vector is `rep(TRUE, n.objectives)` by default.
To figure out if a given global optimum is a minimum or maximum, the `getGlobalOptimum` function now returns an additional field `is.minimum`.
```splus
fn = makeAlpine02Function(dimensions = 2L)
getGlobalOptimum(fn)$is.minimum
# returns FALSE
```
Shall I add a convenience function `shouldBeMinimized` as well?

**Comment by jakobbossek** [comment]
ping

**Comment by giuseppec** [comment]
I think, a Tag "minimize" or "maximize" would also be cool.

**Comment by jakobbossek** [comment]
Ok, going to think about that.

**Comment by berndbischl** [comment]
> Shall I add a convenience function shouldBeMinimized as well?

I really dont need this. But add the info to the printer.

> I think, a Tag "minimize" or "maximize" would also be cool.

Huh? I tought JR added extactly that now?

**Comment by jakobbossek** [comment]
> Huh? I tought JR added extactly that now?

I did not add a tag, but another attribute.
And I am JB :wink:

**Comment by berndbischl** [comment]
oops. sorry :)
well, the point is that the info is there now, right?
that is enough for me. 

also, if you allow "mixes" of min/max for mutiple objectives, it is harder to come up with a single tag? at least for multicrit?

**Comment by jakobbossek** [comment]
Yes, exactly. That's why I did not extend the tag mechanism in this way. The tag `minimize` would be exclusive for single-objective, which is not a good solution in my opinion.

**Comment by berndbischl** [comment]
like i said, i guess for us it is ok now.

check a bit on your side then close IMHO

**Comment by jakobbossek** [comment]
Implemented and tested. Closing.
