### ISSUE TITLE
Remove dimensions from makeUFFunction

### ISSUE THREAD

**Issue by lkreft** [jakobbossek/smoof#57]
I would really like to remove the `dimensions` parameter from the UFx functions because it would provide much more flexiblity in their use. We could easily get rid of it by calculating `r_dimensions` from `r_x.size()` at the [cec09 r-to-c interface](../blob/master/src/cec09_r_to_c_interface.c).

The problem is, though, that the lower and upper bounds would not be displayed as before. My suggestion is to replace e.g. `c(0, rep(-1, dimensions - 1L))` with `c("0", "-1", "...", "-1")`.

Nevertheless, if this is not an option for you, we should definitely add a `stopifnot(length(x) == dimensions)` to the function definition `fn`of `makeUFFunction` because it's broken at the moment:

```R
> uf2_3 = makeUFFunction(3,2)
> uf2_5 = makeUFFunction(5,2)
> uf2_3(rep(0.2, 3))
[1] 0.2365430 0.5695384
> uf2_3(rep(0.2, 5))
[1] 0.2365430 0.5695384
> uf2_5(rep(0.2, 5))
[1] 0.2884053 0.5835806
```

Edit: would really love to add the labels "Suggestion", "Bug" and "Enhancement" here...

**Comment by jakobbossek** [comment]
> I would really like to remove the dimensions parameter from the UFx functions because it would
> provide much more flexiblity in their use. We could easily get rid of it by calculating r_dimensions from
>  r_x.size() at the cec09 r-to-c interface.

> The problem is, though, that the lower and upper bounds would not be displayed as before. My 
> suggestion is to replace e.g. c(0, rep(-1, dimensions - 1L)) with c("0", "-1", "...", "-1"). 
Yes we could do this, but for consistency reasons the I will not change the interface here.
Moreover, the solution proposed for the lower/upper bounds is not satisfactory, since this should always be a numeric vector.

However, adding the sanity check to the function body is a good idea. Going to add it to all functions.
