### ISSUE TITLE
plot functions should display name of function as title

### ISSUE THREAD

**Issue by berndbischl** [jakobbossek/smoof#67]
this should be done by default, with an option to switch it off

do you already support plotting on log-scale / with a trafo?

that is often needed

**Comment by jakobbossek** [comment]
Regarding the plot title: I can add this option to the default plot functions. But for the ggplot functions I prefer to add a title via `myPlot + ggtitle(myFun$name)`.

Trafos are not yet supported.

**Comment by berndbischl** [comment]
It is hard to decide whether you want the user to do this or do this internally.
But personally I would say: I would add an option, also for ggplot2, and do it by default. 
You nearly always want to see it.

Stuff like logTrafos are pretty important for the plot so you can see what goes on

**Comment by jakobbossek** [comment]
We now have a `main` parameter for `plot` and `autoplot` with default `getName(x)`, i.e., the name of the function at hand.
