### ISSUE TITLE
maybe functions should have ids

### ISSUE THREAD

**Issue by berndbischl** [jakobbossek/smoof#68]
very often you would like to put stuff into files or hashtables / list, where we index by function.
using the name / getName is not so nice, because it has spaces and so on.
Having a unique, simple ID would be great: eg ackley2d.

**Comment by jakobbossek** [comment]
Good idea. Going to implement this soon.

**Comment by jakobbossek** [comment]
Well, should the ID be a obligatory parameter in your opinion? I do not want to add any additional mandatory parameters which bloat the creation of functions. However, we could make it optional and I could add an ID for each predefined function.

**Comment by berndbischl** [comment]
Ensure that it's there for all smoof pkg functions. But make it optional for temp fun des in tryout code.

Also add a getter for the id.

**Comment by jakobbossek** [comment]
Finished in about 10 minutes.

**Comment by berndbischl** [comment]
I wanted to write : temp function definitions. Sorry. On mobile.

**Comment by jakobbossek** [comment]
Underscores should be ok in IDs?

**Comment by jakobbossek** [comment]
Ok. Done. For "multi-word" functions like Styblinski-Tang the corresponding ID is styblinskiTang_2d.
Functions with additional parameter like Michalewicz function with steepness parameter the ID is e.g. michalewicz_5d_m10. There is a `getID` method as well.

**Comment by berndbischl** [comment]
all of what you write is totally good and OK! thx
