### ISSUE TITLE
getParamSet name clash

### ISSUE THREAD

**Issue by berndbischl** [jakobbossek/smoof#73]
we now completely depend on smoof in mlrMBO

but your function shadows the one in mlr. 

is there any chance to resolve this here

(not that we cannot import smoof, as the user needs it now the NS to construct the function, just as you suggested....)

**Comment by berndbischl** [comment]
General note, this might be too late for your package, but I more and more tend towards the style
getClassnameMembervar

**Comment by jakobbossek** [comment]
Until now only some of my packages make use of smoof. So I can rename it into `getParameterSet`.
I am not willing to rename all stuff in the way you proposed.

However, is the shadowing really a problem if we use the smoof:: prefix everytime we call this function?

**Comment by berndbischl** [comment]
The problem is not for "us". 
It is for users who dont understand or see the shadowing.

I would suggest a more precise name. getSmoofFunctionParamSet. getSFParamSet.
getParameterSet looks too similar

**Comment by jakobbossek** [comment]
Well, to stay consistent it would be necessary to include this Namespace to each of the smoof (getter) functions, right?

**Comment by berndbischl** [comment]
You already told me you dont want to do that. But just because we use SF here in the name does not make it a general rule? 
It you really hate, I maybe use at least getPS.

**Comment by jakob-r** [comment]
I'm favoring getLearnerParamSet in mlr ;) Makes it also easier to find for the user.

**Comment by berndbischl** [comment]
Yes, but mlr is used by many people at the moment. We have 0 chance of renaming this. 
Only in mlr2 or whatever, so this does not solve our problem now.

**Comment by mllg** [comment]
My proposal: Implement the generic method in `ParamHelpers` so nobody has to rename anything.

**Comment by jakob-r** [comment]
@berndbischl But who uses getParamSet in a working scenario and how could it be used in a working scenario?

**Comment by berndbischl** [comment]
> My proposal: Implement the generic in ParamHelpers so nobody has to rename anything.

This is against the guidelines we already discussed

**Comment by berndbischl** [comment]
We agrreed that having the generic in PH might be best here. Is that ok for you @jakobbossek?

But please. Let us only do this in in special case. It is not a catch-all to deal with general problem, and will introduce horrible problems if we now habe generic APIs across multiple packages.

**Comment by jakobbossek** [comment]
This is ok for me.

**Comment by berndbischl** [comment]
I will do this tonite then in PH on GH

**Comment by jakobbossek** [comment]
Is this done?

**Comment by mllg** [comment]
As discussed earlier, we now have a generic getParamSet in ParamHelpers. Please consider (a) an import/re-export of the generic or (b) removing your generic and updating the dependencies.

**Comment by berndbischl** [comment]
Hi, we discussed this earlier. I asked "will this introduce problems". The added generic in PH now breaks mlr on CRAN. This happens way too often anyhow.

To be honest, I really dont want this. This is exactly what I meant here

"It is not a catch-all to deal with general problem, and will introduce horrible problems if we now habe generic APIs across multiple packages."

We now have an API change, which is even against the structure/naming system we want to strive for in the future, and have to fix MULTIPLE packages for this, breaking stuff on CRAN.

**Comment by jakobbossek** [comment]
Ok. Then I will rename to `getSmoofParamSet` and by the way introduce the smoof namespace in all the other smoof helper functions in order to avoid problems in the future. Is this ok for you @berndbischl?

**Comment by berndbischl** [comment]
Give me 24h to reply. After that you can call me hourly on my phone to force a decision.

**Comment by jakobbossek** [comment]
Ok :+1:

**Comment by jakobbossek** [comment]
ping

**Comment by jakob-r** [comment]
He said :telephone_receiver:

**Comment by jakobbossek** [comment]
We are going to discuss that issue tomorrow.

**Comment by jakobbossek** [comment]
@berndbischl You wanted to upload the new ParamHelpers version to CRAN last weekend.

**Comment by mllg** [comment]
@berndbischl is going to upload PH tomorrow :wink:

You might need to update smoof accordingly. If you have any objections, please contact us ASAP.

**Comment by jakobbossek** [comment]
Ok. So I need to get rid of my getParamSet function and depend on PH1.8?

**Comment by berndbischl** [comment]
> Ok. So I need to get rid of my getParamSet function and depend on PH1.8?

yes please. you can already depend on the github version. @mllg and I are finalizing PH now for CRAN. 
if michel's cleanups are done, we can push to cran, should hopefully be today

**Comment by jakob-r** [comment]
I did PR #87

**Comment by jakobbossek** [comment]
Thanks. Closing.
