### ISSUE TITLE
mistake in sof.bukin.n2.R

### ISSUE THREAD

**Issue by jakob-r** [jakobbossek/smoof#82]
There are several inconsistencies in named function.

* x_1 in [15-5] as stated in the man part but between (-15, -5) in the par.set
* global op params definately not at the optimum position

Unfortunately the source is paywalled in my university so i cannot check what is right.

**Comment by jakobbossek** [comment]
Thanks.
1) x_1 in [-15, -5] is correct
2) I have two sources for the Bukin02 functions and both define the same analytic formula
f(x) = 100(x_2 + 0.01x_1^2 + 1) + 0.01(x_1 + 10)^2
(see e.g., http://infinity77.net/global_optimization/test_functions_nd_B.html)
However, f(-10, 0) is not the minimum for sure for this definition and the plot has no parabola shape in x_2 direction. Thus, I assume that x_2 needs to be squared in the formula. Doing this the plot resembles the one on the webpage and in this case x = (-10, 0) is actually the global optimum.
What do you think?

**Comment by jakob-r** [comment]
If I use `100 * (x[2]^2 - 0.01 * x[1]^2 + 1) + 0.01 * (x[1] + 10)^2` then it looks like on the website but still the global optimum is not x = (-10,0) but rather x = (0, -15).

**Comment by jakobbossek** [comment]
you are right

**Comment by jakobbossek** [comment]
Determined the optimum with ecr and x = (-15, 0) seems to be the optimum.

**Comment by jakobbossek** [comment]
Fixed
