### ISSUE TITLE
implement discrete functions

### ISSUE THREAD

**Issue by jakob-r** [jakobbossek/smoof#83]
I will just paste it here for discussion and so it does not get lost:

``` r
test.function.zhou2011 = function(x, category) {
  if (category == "a") return(cos(6.8*pi*(x/2)))
  if (category == "b") return(-cos(7*pi*(x/2)))
  if (category == "c") return(cos(7.2*pi*(x/2)))
}
```

A Simple Approach to Emulation for Computer Models With Qualitative and Quantitative Factors
Qiang Zhou , Peter Z. G. Qian , Shiyu Zhou 
Technometrics 
Vol. 53, Iss. 3, 2011
http://amstat.tandfonline.com/doi/abs/10.1198/TECH.2011.10025

``` r
test.function.swiler2014 = function(x, category) {
  if (category == "a") return(sin(2 * pi * x[2] - pi) + 7 * sin(2 * pi * x[1] - pi) ^ 2)
  if (category == "b") return(sin(2 * pi * x[2] - pi) + 7 * sin(2 * pi * x[1] - pi) ^ 2 + 0.5 * sin(2 * pi * x[2] - pi))
  if (category == "c") return(sin(2 * pi * x[2] - pi) + 7 * sin(2 * pi * x[1] - pi) ^ 2 + 0.8 * sin(2 * pi * x[2] - pi))
  if (category == "d") return(sin(2 * pi * x[2] - pi) + 7 * sin(2 * pi * x[1] - pi) ^ 2 + 8 * sin(2 * pi * x[2] - pi))
  if (category == "e") return(sin(2 * pi * x[2] - pi) + 7 * sin(2 * pi * x[1] - pi) ^ 2 + 3.5 * sin(2 * pi * x[2] - pi))
}
```

Surrogate models for mixed discrete-continuous variables
Laura P. Swiler, Patricia D. Hough, Peter Qian, Xu Xu, Curtis Storlie, Herbert Lee
https://cfwebprod.sandia.gov/cfdocs/CompResearch/docs/MixedSurrSAND2012-0491.pdf

In both cases x in [0,1] I think.

I can maka a PR if you want.

**Comment by jakobbossek** [comment]
Going to implement these functions soon. Let's talk about that on the LION conference 👍

**Comment by jakobbossek** [comment]
Implemented Swiler2014.

**Comment by jakobbossek** [comment]
Closing for now.
