### ISSUE TITLE
covariance matrices of mpm2-peaks

### ISSUE THREAD

**Issue by kerschke** [jakobbossek/smoof#91]
Can we (= you ;)) somehow (easily) return the covariance matrices of the (elliptical shaped) peaks of the mpm2-functions? I could imagine something like adding a list of covariance matrices (one per peak) to the information that one already receives by calling `getLocalOptimum`. I presume that each covariance matrix is stored within `peak.D` (in the file `mpm2.py`).

**Comment by kerschke** [comment]
I think, I might have some sort of (initial) solution for it. Within the main part of `mpm2.py` we simply add the following function:
```{python}
    def getCovMatrices(self):
        peaks = self.peaks
        res = []
        for peak in peaks:
            X = peak.D
            X = X.reshape(len(X) * len(X[0]))
            res.append(np.matrix(X).tolist())
        return res
```

And then, we also define an additional getter-function:

```{python}
def getCovarianceMatrices(npeaks, dimension, topology, randomSeed, rotated, peakShape):
    global currentProblem
    initProblem(npeaks, dimension, topology, randomSeed, rotated, peakShape)
    return currentProblem.getCovMatrices()
```

This way, python now returns a list of vectors, where each vector contains the elements of the covariance matrix.

So now, I can use those vectors for now and you have more time to consider, whether you think it's useful to integrate the covariance matrices as part of the function attributes :)

**Comment by jakobbossek** [comment]
Done
