### ISSUE TITLE
error in CosineMixtureFunction optimum

### ISSUE THREAD

**Issue by jakob-r** [jakobbossek/smoof#92]
```r
ggplot2::autoplot(makeCosineMixtureFunction(1), show.optimum = TRUE)
```
![image](https://cloud.githubusercontent.com/assets/1888623/21590983/7b3b1502-d100-11e6-8301-9fc257bd28c7.png)

**Comment by jakobbossek** [comment]
Thanks for posting. This was due to a faulty minus sign before the first term of of the function definition in this source: https://arxiv.org/pdf/1308.4008.pdf.
Looked into the referenced original publications and fixed the bug.
