### ISSUE TITLE
Error description when using wrong dimension

### ISSUE THREAD

**Issue by hansterc** [jakobbossek/smoof#96]
When creating a function which requires 2 dimensions explicitly but you try to create it with only one (dimensions=1). The error message which is displayed is: 
"Dimension > 3 passed, but 'Adjiman' is a non-scalable 2D function." 

Better would be something like "Dimensions !=2 passed". 

The code I used to create the error was: 
`makeFunctionsByName("Adjiman", dimensions=1)`

**Comment by jakobbossek** [comment]
Thanks for reporting. Changed the message to "Dimension attribute passed, but Adjiman is a non-scalable function".
