### ISSUE TITLE
help text of " makeSingleObjectiveFunction {smoof}" in R

### ISSUE THREAD

**Issue by uwesterr** [jakobbossek/smoof#98]
hi,
i have version 1.4 of smooth installed. the "bug" is in the help text 
`fn.num2 = makeSingleObjectiveFunction(
  name = "Numeric 2D",   
  fn = function(x) sum(x^2),   
  par.set = makeParamSet(   
    makeNumericParam("x1", lower = -5, upper = 5),
    makeNumericParam("x2", lower = -10, upper = 20)
  )
)
print(fn)  
print(autoplot(fn))`

in the last two lines "fn" should be replace by "fn.num2", it reads then 
`print(fn.num2)
print(autoplot(fn.num2))
`
same issue with the next example in the help text for fn.mixed

thanks for your great package

uwe

**Comment by jakobbossek** [comment]
Thanks! Fixed.
